executable              = exeCoverageFH.sh
arguments               = $(njob_) 

output                  = out_coverage/CI.$(bin_)_$(step_).$(ClusterId).$(ProcId).out
error                   = err_coverage/CI.$(bin_)_$(step_).$(ClusterId).$(ProcId).err
log                     = log_coverage/CI.$(bin_)_$(step_).$(ClusterId).log
+JobFlavour             = "testmatch"

queue njob_ from runsCoverage.txt